server:
  port: 8888

app:
  base-url: ${BASE_URL:http:localhost:8888}
  pay-u:
    url: ${PAYU_URL:https://merch-prod.snd.payu.com}
    pos-id: ${PAYU_POS_ID:300746}
    md5: ${PAYU_MD5:b6ca15b0d1020e8094d9b5f8d163db54}
    client-id: ${PAYU_CLIENT_ID:300746}
    client-secret: ${PAYU_CLIENT_SECRET:2ee86a66e5d97e3fadc400c9f19b065d}
    notification-secret: ${PAYU_NOTIFICATION_SECRET:superSecretForNotification}
